include: package:lint/analysis_options.yaml

# linter:
#   rules:
#     [rule]: [true/false]

analyzer:
  errors:
#   [rule]: [warning/ignore/info/error]
    parameter_assignments: error
    missing_required_param: error
    must_be_immutable: error
    missing_return: error
    