import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import 'package:highlights/injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Global dependency injection management
///
/// The injectable package uses get_it internally to provide the dependencies
/// for all the classes of the project. Annotations are used to identify the
/// injectable classes. Then, code is autogenerated with build_runner
@InjectableInit()
void configureInjection() {
  $initGetIt(getIt);
}
